modules:
  esignet-signup:
    enabled: true
    image:
      repository: mosipid/apitest-esignet-signup
      tag: 1.2.2
      pullPolicy: Always

extraEnvVarsCM:
  - esignet-global
  - s3
  - keycloak-host
  - db
  - apitestrig

extraEnvVarsSecret:
  - apitestrig-esignet-signup-apitestrig
  - s3-esignet-signup-apitestrig
  - keycloak-client-secrets
  - postgres-postgresql

apitestrig:
  configmaps:
    apitestrig:
       #mosip_components_base_urls: idrepository=api-internal.sandbox.mosip.net;idauthentication=api-internal.sandbox.mosip.net;masterdata=api-internal.sandbox.mosip.net;idgenerator=api-internal.sandbox.mosip.net;authmanager=api-internal.sandbox.mosip.net;auditmanager=api-internal.sandbox.mosip.net;resident=api-internal.sandbox.mosip.net;keymanager=api-internal.sandbox.mosip.net;


resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 300m
    memory: 500Mi
